In [12]:
import pyarrow.parquet as pq

# Read the parquet file
table = pq.read_table('trade_summary_1h_hour_15.parquet')

# Convert to pandas DataFrame if needed
df = table.to_pandas()

# Display the first few rows
df.head()

,fetched_at,price_min,price_max,price_avg,total_volume,avg_trade_size,trade_count,buy_volume,sell_volume,symbol,date,bucket
0,2025-07-11 15:00:00+00:00,117434.99,117819.59,117652.06062,41.966549,0.020983,2000,889,1111,BTC-USD,2025-07-11,1h

In [14]:
import pyarrow.parquet as pq

# Read the parquet file
table = pq.read_table('trade_summary_1h_hour_17.parquet')

# Convert to pandas DataFrame if needed
df_ = table.to_pandas()

# Display the first few rows
df_.head()

,fetched_at,price_min,price_max,price_avg,total_volume,avg_trade_size,trade_count,buy_volume,sell_volume,symbol,date,bucket
0,2025-07-11 17:00:00+00:00,117276.49,117410.04,117356.91986,32.04822,0.032048,1000,527,473,BTC-USD,2025-07-11,1h

In [16]:
# Read the parquet file
table1 = pq.read_table('trade_summary_30min_hour_15.parquet')

# Convert to pandas DataFrame if needed
df_30 = table1.to_pandas()

# Display the first few rows
df_30.head()

,fetched_at,price_min,price_max,price_avg,total_volume,avg_trade_size,trade_count,buy_volume,sell_volume,symbol,date,bucket
0,2025-07-11 15:00:00+00:00,117699.16,117819.59,117781.53343,28.222276,0.028222,1000,417,583,BTC-USD,2025-07-11,30min
1,2025-07-11 15:30:00+00:00,117434.99,117624.45,117522.58781,13.744273,0.013744,1000,472,528,BTC-USD,2025-07-11,30min

In [17]:
# Read the parquet file
table1 = pq.read_table('trade_summary_30min_hour_16.parquet')

# Convert to pandas DataFrame if needed
df_30_ = table1.to_pandas()

# Display the first few rows
df_30_.head()

,fetched_at,price_min,price_max,price_avg,total_volume,avg_trade_size,trade_count,buy_volume,sell_volume,symbol,date,bucket
0,2025-07-11 16:30:00+00:00,117295.2,117451.12,117367.58643,16.65941,0.016659,1000,423,577,BTC-USD,2025-07-11,30min